Multi file joli
NZ-MRDP/q2-snpSift pull request #11
Opened 2024-01-23 19:33 UTC by mchenaux

2024-01-23 21:10 UTC, HenziKou requested changes

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/_snpsift.py
> +            executable_path,
Remove trailing whitespace.

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/_transformer.py
> +        executable_path,
Remove trailing whitespace

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/_snpsift.py
> +            executable_path,
Indent everything inside the `cmd` brackets by one tab level.

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/_transformer.py
> +        executable_path,
Indent everything inside the `cmd` brackets by one tab level.

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/_snpsift.py
> +                              VariantCallFile, VCFIndexDirectory, VCFIndexFile)
Remove unused import `VCFIndexFile`

2024-01-23 21:10 UTC, HenziKou commented on q2_snpsift/plugin_setup.py
> +                              VariantCallFile, Variants)
Remove unused import `VariantCallFile`

2024-01-29 19:01 UTC, HenziKou requested changes

2024-01-31 18:22 UTC, mchenaux commented on q2_snpsift/_transformer.py
Ok, so in the past couple of days I ran through the entire pipeline again in 2022.11 and got the whole thing working. There was a problem with the config file, which I regenerated. The 2022.11 qzas can be found here https://novozymes.sharepoint.com/:f:/r/sites/zynergy_3000031/Shared%20Documents/Variant_Calling_Pipeline/test_data?csf=1&web=1&e=XmdCFt including the config file that works.

2024-02-01 22:20 UTC, mchenaux commented on q2_snpsift/_transformer.py
Ok I think i figured this out. I made a change in q2-types-variant on branch multi-sample that fixes this. It allows multiple files and names in the output. So, do we wait for that to be merged to main?

2024-02-02 17:16 UTC, merged